controller_manager:
  ros__parameters:
    update_rate: 30

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    uvc_controller:
      type: uvc_robot_controller/UVC_Controller

imu_sensor_broadcaster:
  ros__parameters:

    sensor_name: "imu_sensor"
    frame_id:  "imu_link"